export enum ExportSelectEnum {
  TEACHER_PERSONAL_INFO = 'TEACHER_PERSONAL_INFO',
  TEACHER_PROFESSIONAL_INFO = 'TEACHER_PROFESSIONAL_INFO',
  HONORS = 'HONORS',
  REBUKES = 'REBUKES',
  INTERNSHIPS = 'INTERNSHIPS',
  PUBLICATIONS = 'PUBLICATIONS',
  ATTESTATIONS = 'ATTESTATIONS'
}
