export enum WorksheetEnum {
  TEACHER_PERSONAL_AND_PROFESSIONAL = 1,
  TEACHER_PROFESSIONAL = 2,
  TEACHER_PERSONAL = 3,
  INTERNSHIP = 4,
  ATTESTATION = 5,
  PUBLICATION = 6,
  HONOR = 7,
  REBUKE = 8
}