export enum TeacherImportColumnsEnum {
  FULL_NAME = 1,
  EMAIL = 2,
  BIRTHDAY = 3,
  PHONE = 4,
  ADDRESS = 5,
  DEPARTMENT = 6,
  COMMISSION = 7,
  TEACHING_RANK = 8,
  ACADEMIC_DEGREE = 9,
  ACADEMIC_TITLE = 10,
  WORK_START_DATE = 11,
}
