export enum ImportDataTypeEnum {
  USER = 'USER',
  TEACHER = 'TEACHER',
  INTERNSHIP = 'INTERNSHIP',
  HONOR = 'HONOR',
  REBUKE = 'REBUKE',
  PUBLICATION = 'PUBLICATION',
  ATTESTATION = 'ATTESTATION',
  EDUCATION = 'EDUCATION'
}
